name: myheadsyle
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0 # Mendukung range luas

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase - Gunakan versi terbaru agar bug Pigeon hilang
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.0

  # Network & Image
  http: ^1.1.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # PENTING: Daftarkan logo kamu disini agar tidak error saat login
  assets:
    - assets/logo.png